export const LIST_REQUEST  = 'LIST_REQUEST';
export const LIST_FAILTURE = 'LIST_FAILTURE';
export const LIST_SUCCESS  = 'LIST_SUCCESS';
export const SERVICE_REQUEST  = 'SERVICE_REQUEST';
export const SERVICE_FAILTURE = 'SERVICE_FAILTURE';
export const SERVICE_SUCCESS  = 'SERVICE_SUCCESS';
